/** Core palette — raw values (reference only, prefer semantic tokens) */
export declare const palette: {
    readonly white: "#ffffff";
    readonly black: "#000000";
    readonly gray50: "#f9fafb";
    readonly gray100: "#f3f4f6";
    readonly gray200: "#e5e7eb";
    readonly gray300: "#d1d5db";
    readonly gray400: "#9ca3af";
    readonly gray500: "#6b7280";
    readonly gray600: "#4b5563";
    readonly gray700: "#374151";
    readonly gray800: "#1f2937";
    readonly gray900: "#111827";
    readonly primary50: "#eff6ff";
    readonly primary100: "#dbeafe";
    readonly primary200: "#bfdbfe";
    readonly primary300: "#93c5fd";
    readonly primary400: "#60a5fa";
    readonly primary500: "#3b82f6";
    readonly primary600: "#2563eb";
    readonly primary700: "#1d4ed8";
    readonly primary800: "#1e40af";
    readonly primary900: "#1e3a8a";
    readonly green50: "#f0fdf4";
    readonly green500: "#22c55e";
    readonly green700: "#15803d";
    readonly amber50: "#fffbeb";
    readonly amber500: "#f59e0b";
    readonly amber700: "#b45309";
    readonly red50: "#fef2f2";
    readonly red500: "#ef4444";
    readonly red700: "#b91c1c";
    readonly blue50: "#eff6ff";
    readonly blue500: "#3b82f6";
    readonly blue700: "#1d4ed8";
};
/** Semantic token contract — maps intent to CSS custom property names */
export declare const semanticColorTokens: {
    readonly "surface-default": "--surface-default";
    readonly "surface-canvas": "--surface-canvas";
    readonly "surface-muted": "--surface-muted";
    readonly "surface-raised": "--surface-raised";
    readonly "text-primary": "--text-primary";
    readonly "text-secondary": "--text-secondary";
    readonly "text-disabled": "--text-disabled";
    readonly "text-inverse": "--text-inverse";
    readonly "border-default": "--border-default";
    readonly "border-subtle": "--border-subtle";
    readonly "border-strong": "--border-strong";
    readonly "action-primary": "--action-primary";
    readonly "action-primary-hover": "--action-primary-hover";
    readonly "action-primary-active": "--action-primary-active";
    readonly "action-secondary": "--action-secondary";
    readonly "state-success-bg": "--state-success-bg";
    readonly "state-success-text": "--state-success-text";
    readonly "state-warning-bg": "--state-warning-bg";
    readonly "state-warning-text": "--state-warning-text";
    readonly "state-error-bg": "--state-danger-bg";
    readonly "state-error-text": "--state-danger-text";
    readonly "state-info-bg": "--state-info-bg";
    readonly "state-info-text": "--state-info-text";
};
export type SemanticColorToken = keyof typeof semanticColorTokens;
