import type { DesignLabComponentDocEntry } from '../types';

const entry: DesignLabComponentDocEntry = {
  name: 'ApprovalInbox',
  indexItem: {
    name: 'ApprovalInbox',
    kind: 'component',
    availability: 'exported',
    lifecycle: 'stable',
    maturity: 'beta',
    group: 'ai_helpers',
    subgroup: 'approval_audit',
    taxonomyGroupId: 'ai_native_helpers',
    taxonomySubgroup: 'Approval / Audit',
    demoMode: 'live',
    description:
      'Bekleyen onaylar inbox yuzeyi: inline filtre + ApprovalCheckpoint density=compact x map + per-row ApprovalEligibilityGuard (4-eyes) + inline bulk action bar (eligibleIds + blockedReasons split) + Pagination.',
    sectionIds: ['governance_contribution', 'integration_distribution', 'documentation_standards'],
    qualityGates: [
      'design_tokens',
      'preview_visibility',
      'registry_export_sync',
      'ux_catalog_alignment',
      'a11y_keyboard_support',
    ],
    tags: ['wave-12', 'approval-foundation', 'beta', 'approval', 'recipe'],
    uxPrimaryThemeId: 'ai_assisted_decision_experience',
    uxPrimarySubthemeId: 'human_approval_checkpoints',
    roadmapWaveId: 'wave_12_approval_foundation',
    acceptanceContractId: 'ui-library-wave-12-approval-foundation-v1',
    importStatement: "import { ApprovalInbox } from '@mfe/design-system';",
    whereUsed: [],
    dependsOn: [
      'ApprovalCheckpoint',
      'ApprovalEligibilityGuard',
      'Pagination',
      'Button',
      'Badge',
      'Text',
    ],
  },
  apiItem: {
    name: 'ApprovalInbox',
    variantAxes: [
      'filters: controlled | uncontrolled',
      'access: full | readonly | hidden',
      'pagination: server-side | client-side',
    ],
    stateModel: [
      'selected request ids',
      'filter state (query / type / status)',
      'current page (when controlled)',
    ],
    previewStates: [
      'empty',
      'populated-mixed-statuses',
      'with-bulk-selection',
      'with-4-eyes-block',
      'readonly-access',
    ],
    behaviorModel: [
      'Per-row eligibility: proposer===currentUser flags proposer_self',
      'Bulk callbacks receive { eligibleIds, blockedReasons } split',
      'Inline filters update query/type/status (controlled or internal)',
      'Pagination only renders when total > pageSize',
    ],
    props: [
      {
        name: 'requests',
        type: 'ApprovalRequest[]',
        default: '-',
        required: true,
        description: 'Render edilecek talep listesi.',
      },
      {
        name: 'currentUser',
        type: 'ApprovalActor',
        default: '-',
        required: true,
        description: 'Aktif kullanici; per-row eligibility hesaplamasinda kullanilir.',
      },
      {
        name: 'filters',
        type: 'ApprovalInboxFilters',
        default: '-',
        required: false,
        description: 'Controlled filtre state.',
      },
      {
        name: 'onFiltersChange',
        type: '(next) => void',
        default: '-',
        required: false,
        description: 'Filtre callback (controlled mode).',
      },
      {
        name: 'onRequestOpen',
        type: '(request) => void',
        default: '-',
        required: false,
        description: 'Row primary action callback.',
      },
      {
        name: 'onBulkApprove',
        type: '(payload: { eligibleIds, blockedReasons }) => void',
        default: '-',
        required: false,
        description: 'Toplu onay; eligible/blocked split payload.',
      },
      {
        name: 'onBulkReject',
        type: '(payload: { eligibleIds, blockedReasons }) => void',
        default: '-',
        required: false,
        description: 'Toplu red; eligible/blocked split payload.',
      },
      {
        name: 'page',
        type: 'number',
        default: '-',
        required: false,
        description: 'Controlled mevcut sayfa.',
      },
      {
        name: 'pageSize',
        type: 'number',
        default: '25',
        required: false,
        description: 'Sayfa boyutu.',
      },
      {
        name: 'total',
        type: 'number',
        default: '-',
        required: false,
        description: 'Toplam talep sayisi (server pagination icin).',
      },
      {
        name: 'access',
        type: 'AccessLevel',
        default: 'full',
        required: false,
        description: 'Erisim seviyesi.',
      },
    ],
    previewFocus: ['bulk split semantics', '4-eyes row blocking', 'inline filter ergonomics'],
    regressionFocus: [
      'proposer_self flagged when proposer===currentUser',
      'Bulk payload reset after dispatch',
      'Empty state copy',
    ],
  },
};

export default entry;
