import type { DesignLabComponentDocEntry } from '../types';

const entry: DesignLabComponentDocEntry = {
  name: 'ApprovalRequestForm',
  indexItem: {
    name: 'ApprovalRequestForm',
    kind: 'component',
    availability: 'exported',
    lifecycle: 'stable',
    maturity: 'beta',
    group: 'ai_helpers',
    subgroup: 'approval_audit',
    taxonomyGroupId: 'ai_native_helpers',
    taxonomySubgroup: 'Approval / Audit',
    demoMode: 'live',
    description:
      '3 adimli onay talebi gonderme formu; Steps + useForm + ConnectedFields + AssigneePicker (4-eyes excludeIds) ile gerekce ve onaylayan seciminin governance kaydini olusturur.',
    sectionIds: ['governance_contribution', 'integration_distribution', 'documentation_standards'],
    qualityGates: [
      'design_tokens',
      'preview_visibility',
      'registry_export_sync',
      'ux_catalog_alignment',
      'a11y_keyboard_support',
    ],
    tags: ['wave-12', 'approval-foundation', 'beta', 'approval', 'recipe'],
    uxPrimaryThemeId: 'ai_assisted_decision_experience',
    uxPrimarySubthemeId: 'human_approval_checkpoints',
    roadmapWaveId: 'wave_12_approval_foundation',
    acceptanceContractId: 'ui-library-wave-12-approval-foundation-v1',
    importStatement: "import { ApprovalRequestForm } from '@mfe/design-system';",
    whereUsed: [],
    dependsOn: [
      'Steps',
      'Button',
      'Text',
      'Badge',
      'useForm',
      'ConnectedInput',
      'ConnectedTextarea',
      'ConnectedSelect',
      'AssigneePicker',
    ],
  },
  apiItem: {
    name: 'ApprovalRequestForm',
    variantAxes: ['mode: create | edit-draft', 'access: full | readonly | hidden'],
    stateModel: ['current step (0-2)', 'form values + dirty + touched', 'evidence-ref draft input'],
    previewStates: [
      'empty-basics',
      'filled-basics',
      'filled-justification',
      'approvers-step',
      'busy-submission',
    ],
    behaviorModel: [
      'Step gate: cannot advance unless step is valid',
      'Approvers step requires >=1 actor; deadline (if set) must be future',
      'Submit fires onSubmit with discriminated draft (no server-issued fields)',
      'AssigneePicker excludes proposer id (4-eyes)',
    ],
    props: [
      {
        name: 'candidates',
        type: 'ApprovalActor[]',
        default: '-',
        required: true,
        description: 'Onaylayan adayi havuzu.',
      },
      {
        name: 'proposer',
        type: 'ApprovalActor',
        default: '-',
        required: true,
        description: 'Talebi olusturan kullanici; aday listesinden dislanir.',
      },
      {
        name: 'requestTypes',
        type: 'ApprovalRequestType[]',
        default: '-',
        required: true,
        description: 'Onceden tanimli talep tipleri.',
      },
      {
        name: 'initialValues',
        type: 'Partial<ApprovalRequestDraft>',
        default: '-',
        required: false,
        description: 'Taslak duzenleme icin baslangic degerleri.',
      },
      {
        name: 'onSubmit',
        type: '(draft: ApprovalRequestDraft) => void | Promise<void>',
        default: '-',
        required: true,
        description: 'Talep gonderildiginde discriminated draft yayar.',
      },
      {
        name: 'onCancel',
        type: '() => void',
        default: '-',
        required: false,
        description: 'Iptal callback.',
      },
      {
        name: 'busy',
        type: 'boolean',
        default: 'false',
        required: false,
        description: 'Async submit sirasinda Submit ve Next butonlarini disable eder.',
      },
      {
        name: 'access',
        type: 'AccessLevel',
        default: 'full',
        required: false,
        description: 'Erisim seviyesi.',
      },
    ],
    previewFocus: ['multi-step ergonomics', '4-eyes exclude'],
    regressionFocus: [
      'Step validation gate',
      'Submit only on final step + isFullyValid',
      'Empty form initial state disables Next',
    ],
  },
};

export default entry;
