import type { DesignLabComponentDocEntry } from '../types';

const entry: DesignLabComponentDocEntry = {
  name: 'ApprovalCaseView',
  indexItem: {
    name: 'ApprovalCaseView',
    kind: 'component',
    availability: 'exported',
    lifecycle: 'stable',
    maturity: 'beta',
    group: 'ai_helpers',
    subgroup: 'approval_audit',
    taxonomyGroupId: 'ai_native_helpers',
    taxonomySubgroup: 'Approval / Audit',
    demoMode: 'live',
    description:
      'Tek istek detay yuzeyi: header + metadata strip + gerekce/kanit paneli + opsiyonel side-by-side JSON snapshot karsilastirma + karar gecmisi + opsiyonel CommentThread + sticky aksiyon footer (mode-driven tek DecisionActionDialog + ApprovalEligibilityGuard).',
    sectionIds: ['governance_contribution', 'integration_distribution', 'documentation_standards'],
    qualityGates: [
      'design_tokens',
      'preview_visibility',
      'registry_export_sync',
      'ux_catalog_alignment',
      'a11y_keyboard_support',
    ],
    tags: ['wave-12', 'approval-foundation', 'beta', 'approval', 'recipe'],
    uxPrimaryThemeId: 'ai_assisted_decision_experience',
    uxPrimarySubthemeId: 'human_approval_checkpoints',
    roadmapWaveId: 'wave_12_approval_foundation',
    acceptanceContractId: 'ui-library-wave-12-approval-foundation-v1',
    importStatement: "import { ApprovalCaseView } from '@mfe/design-system';",
    whereUsed: [],
    dependsOn: [
      'DecisionActionDialog',
      'ApprovalEligibilityGuard',
      'CommentThread',
      'JsonViewer',
      'Avatar',
      'AvatarGroup',
      'Badge',
      'Button',
      'Text',
    ],
  },
  apiItem: {
    name: 'ApprovalCaseView',
    variantAxes: [
      'attestation: enabled | disabled (auto-switches primary action)',
      'diff: present | absent (side-by-side JsonViewer)',
      'comments: present | absent',
      'access: full | readonly | hidden',
    ],
    stateModel: ['decisionMode: ApprovalAction | null', 'busy (consumer-controlled)'],
    previewStates: [
      'pending-without-diff',
      'pending-with-diff',
      'attest-flow',
      'proposer-self-blocked',
      'with-history',
    ],
    behaviorModel: [
      'Single DecisionActionDialog instance; mode set by which footer button was clicked',
      'Confirm payload dispatched to action-matching handler (approve/reject/delegate/request_changes/attest)',
      'ApprovalEligibilityGuard banner above footer when current user is the proposer (4-eyes)',
      'attestationStatement present → primary footer action becomes "Beyan et" (attest)',
    ],
    props: [
      {
        name: 'request',
        type: 'ApprovalRequest',
        default: '-',
        required: true,
        description: 'Full request object including history and currentApprovers.',
      },
      {
        name: 'currentUser',
        type: 'ApprovalActor',
        default: '-',
        required: true,
        description: 'Active user; drives 4-eyes eligibility.',
      },
      {
        name: 'comments',
        type: 'Comment[]',
        default: '-',
        required: false,
        description: 'Optional CommentThread entries.',
      },
      {
        name: 'onCommentReply',
        type: '(parentId, content) => void',
        default: '-',
        required: false,
        description: 'CommentThread onReply (parent id preserved).',
      },
      {
        name: 'diff',
        type: '{ before, after, beforeLabel?, afterLabel? }',
        default: '-',
        required: false,
        description: 'Side-by-side JSON snapshots (not semantic diff).',
      },
      {
        name: 'delegateCandidates',
        type: 'ApprovalActor[]',
        default: '[]',
        required: false,
        description: 'Delegate dialog candidate pool.',
      },
      {
        name: 'attestationStatement',
        type: 'string',
        default: '-',
        required: false,
        description: 'When present, primary action becomes attest.',
      },
      {
        name: 'presetRejectReasons',
        type: 'DecisionActionPresetReason[]',
        default: '[]',
        required: false,
        description: 'Reject preset reasons.',
      },
      {
        name: 'onApprove / onReject / onDelegate / onRequestChanges / onAttest',
        type: '(payload) => void | Promise<void>',
        default: '-',
        required: false,
        description: 'Per-action handlers; receive the discriminated payload.',
      },
      {
        name: 'onEligibilityBlocked',
        type: '(info) => void',
        default: '-',
        required: false,
        description: 'Audit telemetry hook.',
      },
      {
        name: 'busy',
        type: 'boolean',
        default: 'false',
        required: false,
        description: 'Async submission guard.',
      },
      {
        name: 'access',
        type: 'AccessLevel',
        default: 'full',
        required: false,
        description: 'Access level.',
      },
    ],
    previewFocus: ['sticky footer ergonomics', 'attestation primary swap', 'diff snapshot layout'],
    regressionFocus: [
      'Single DecisionActionDialog instance reuse',
      '4-eyes banner + button-disabled coupling',
      'History timeline renders DecisionRecord action labels',
    ],
  },
};

export default entry;
