import type { DesignLabComponentDocEntry } from '../types';

const entry: DesignLabComponentDocEntry = {
  name: 'AppSidebar',
  indexItem: {
    name: 'AppSidebar',
    kind: 'component',
    availability: 'exported',
    lifecycle: 'stable',
    maturity: 'stable',
    group: 'navigation',
    subgroup: 'sidebar',
    taxonomyGroupId: 'navigation',
    taxonomySubgroup: 'Sidebar / Shell',
    demoMode: 'live',
    description:
      'Composable, collapsible sidebar compound component with header, nav, search, groups, sections, resizer, and footer slots. Persists state to localStorage, auto-collapses on mobile, and supports keyboard navigation, drag-to-resize, and nested nav items up to 3 levels.',
    sectionIds: [
      'component_library_management',
      'navigation_patterns',
      'accessibility_compliance',
    ],
    qualityGates: [
      'design_tokens',
      'preview_visibility',
      'registry_export_sync',
      'ux_catalog_alignment',
      'a11y_keyboard_support',
    ],
    uxPrimaryThemeId: 'navigation_information_scent',
    uxPrimarySubthemeId: 'orientation_and_wayfinding',
    tags: [
      'wave-2',
      'navigation',
      'stable',
      'sidebar',
      'compound-component',
      'resizable',
    ],
    roadmapWaveId: 'wave_2_navigation',
    acceptanceContractId: 'ui-library-wave-2-navigation-v1',
    importStatement: "import { AppSidebar, useSidebar } from '@mfe/design-system';",
    whereUsed: [
      'web/packages/design-system/src/components/app-sidebar/AppSidebar.stories.tsx',
    ],
  },
  apiItem: {
    name: 'AppSidebar',
    variantAxes: [
      'mode: expanded | collapsed',
      'position: left | right (future)',
    ],
    stateModel: [
      'expanded / collapsed mode',
      'search active / idle',
      'group open / closed',
      'item active / inactive',
      'resizing / idle',
    ],
    previewStates: [
      'default',
      'collapsed',
      'search-active',
      'nested',
      'dark-theme',
    ],
    behaviorModel: [
      'collapse/expand toggle with mode persistence to localStorage',
      'search filter with onChange callback and shortcut hint',
      'keyboard navigation: Escape to collapse, focus-visible ring',
      'drag-to-resize handle with min/max bounds and width persistence',
      'responsive auto-collapse on mobile breakpoint (768px)',
      'nested NavItem rendering up to 3 levels with depth-based indentation',
    ],
    props: [
      {
        name: 'defaultMode',
        type: "'expanded' | 'collapsed'",
        default: "'expanded'",
        required: false,
        description: 'Initial sidebar mode.',
      },
      {
        name: 'storageKey',
        type: 'string',
        default: '-',
        required: false,
        description: 'localStorage key for persisting sidebar mode.',
      },
      {
        name: 'collapsedWidth',
        type: 'number',
        default: '56',
        required: false,
        description: 'Width in pixels when collapsed.',
      },
      {
        name: 'expandedWidth',
        type: 'number',
        default: '260',
        required: false,
        description: 'Width in pixels when expanded.',
      },
      {
        name: 'resizable',
        type: 'boolean',
        default: 'false',
        required: false,
        description: 'Enable drag-to-resize via the Resizer sub-component.',
      },
      {
        name: 'resizeStorageKey',
        type: 'string',
        default: "'sidebar-width'",
        required: false,
        description: 'localStorage key for persisting width when resizable.',
      },
      {
        name: 'minWidth',
        type: 'number',
        default: '200',
        required: false,
        description: 'Minimum width when resizable.',
      },
      {
        name: 'maxWidth',
        type: 'number',
        default: '500',
        required: false,
        description: 'Maximum width when resizable.',
      },
      {
        name: 'className',
        type: 'string',
        default: '-',
        required: false,
        description: 'Additional CSS class for the root aside element.',
      },
      {
        name: 'children',
        type: 'ReactNode',
        default: '-',
        required: true,
        description:
          'Compound children: Header, Search, Nav, Section, Group, NavItem, Separator, Footer, Trigger, Resizer.',
      },
      {
        name: 'aria-label',
        type: 'string',
        default: "'Sidebar'",
        required: false,
        description: 'Accessible label for the sidebar landmark (set on the root aside).',
      },
    ],
    previewFocus: [
      'expanded vs collapsed mode with width transition',
      'compound slot composition: header, search, nav, footer',
      'responsive auto-collapse on mobile breakpoint',
      'search with keyboard shortcut badge',
      'collapsible groups and sections with animation',
      'nested nav items with depth indentation',
      'drag-to-resize with visual handle feedback',
      'tooltip on collapsed items',
    ],
    regressionFocus: [
      'collapse animation timing and width transition',
      'search debounce and filter callback integrity',
      'keyboard roving: Escape collapse, focus-visible ring',
      'resize bounds clamping and width persistence',
      'dark mode token resolution for all sub-components',
      'localStorage persistence round-trip for mode and width',
      'aria-current on active NavItem',
      'aria-expanded on collapsible Group and Section',
    ],
  },
};

export default entry;
