import type { DesignLabComponentDocEntry } from '../types';

const entry: DesignLabComponentDocEntry = {
  name: 'AssigneePicker',
  indexItem: {
    name: 'AssigneePicker',
    kind: 'component',
    availability: 'exported',
    lifecycle: 'stable',
    maturity: 'beta',
    group: 'ai_helpers',
    subgroup: 'approval_audit',
    taxonomyGroupId: 'ai_native_helpers',
    taxonomySubgroup: 'Approval / Audit',
    demoMode: 'live',
    description:
      'Onaylayan / atanan secimi icin avatar + role destekli combobox primitive; 4-eyes icin excludeIds destegi.',
    sectionIds: ['governance_contribution', 'integration_distribution', 'documentation_standards'],
    qualityGates: [
      'design_tokens',
      'preview_visibility',
      'registry_export_sync',
      'ux_catalog_alignment',
      'a11y_keyboard_support',
    ],
    tags: ['wave-12', 'approval-foundation', 'beta', 'approval'],
    uxPrimaryThemeId: 'ai_assisted_decision_experience',
    uxPrimarySubthemeId: 'human_approval_checkpoints',
    roadmapWaveId: 'wave_12_approval_foundation',
    acceptanceContractId: 'ui-library-wave-12-approval-foundation-v1',
    importStatement: "import { AssigneePicker } from '@mfe/design-system';",
    whereUsed: [],
    dependsOn: ['AvatarGroup', 'Badge', 'Text'],
  },
  apiItem: {
    name: 'AssigneePicker',
    variantAxes: ['mode: single | multi', 'size: sm | md | lg', 'showRole: true | false'],
    stateModel: ['search query', 'open listbox', 'selected actor(s)'],
    previewStates: [
      'single-empty',
      'single-selected',
      'multi-three-selected',
      'four-eyes-excluded',
      'readonly-access',
    ],
    behaviorModel: [
      'search filters candidates by name/role/email',
      'ArrowDown moves focus into listbox',
      'Enter on focused option selects',
      'Backspace on empty input drops last (multi)',
      'excludeIds hides candidates and flags stale values',
    ],
    props: [
      {
        name: 'candidates',
        type: 'ApprovalActor[]',
        default: '[]',
        required: true,
        description: 'Secilebilir adaylar.',
      },
      {
        name: 'value',
        type: 'ApprovalActor | ApprovalActor[] | null',
        default: '-',
        required: true,
        description: 'Secili aktor(ler); discriminated by mode.',
      },
      {
        name: 'onChange',
        type: '(next) => void',
        default: '-',
        required: true,
        description: 'Secim degisikliklerini yayar.',
      },
      {
        name: 'mode',
        type: "'single' | 'multi'",
        default: 'single',
        required: false,
        description: 'Tek ya da coklu secim kipi.',
      },
      {
        name: 'excludeIds',
        type: 'string[]',
        default: '[]',
        required: false,
        description: "Listeden gizlenecek aktor id'leri (4-eyes).",
      },
      {
        name: 'showRole',
        type: 'boolean',
        default: 'true',
        required: false,
        description: 'Aktor adi yaninda role etiketini gosterir.',
      },
      {
        name: 'size',
        type: "'sm' | 'md' | 'lg'",
        default: 'md',
        required: false,
        description: 'Bilesen boyut varyanti.',
      },
      {
        name: 'maxVisible',
        type: 'number',
        default: '3',
        required: false,
        description: 'Multi modda avatar group icindeki azami goruntu adedi.',
      },
      {
        name: 'access',
        type: 'AccessLevel',
        default: 'full',
        required: false,
        description: 'Erisim seviyesi.',
      },
    ],
    previewFocus: ['actor selection ergonomics', 'four-eyes blocked badge'],
    regressionFocus: [
      'Backspace empty-input remove (multi)',
      'excludeIds with stale value renders blocked badge',
      'readonly access hides remove controls',
    ],
  },
};

export default entry;
