import type { DesignLabComponentDocEntry } from '../types';

const entry: DesignLabComponentDocEntry = {
  name: 'DecisionActionDialog',
  indexItem: {
    name: 'DecisionActionDialog',
    kind: 'component',
    availability: 'exported',
    lifecycle: 'stable',
    maturity: 'beta',
    group: 'ai_helpers',
    subgroup: 'approval_audit',
    taxonomyGroupId: 'ai_native_helpers',
    taxonomySubgroup: 'Approval / Audit',
    demoMode: 'live',
    description:
      "Approve / reject / delegate / request_changes / attest aksiyonlarini tek dialog API'siyle birlestiren mode-driven karar yuzeyi.",
    sectionIds: ['governance_contribution', 'integration_distribution', 'documentation_standards'],
    qualityGates: [
      'design_tokens',
      'preview_visibility',
      'registry_export_sync',
      'ux_catalog_alignment',
      'a11y_keyboard_support',
    ],
    tags: ['wave-12', 'approval-foundation', 'beta', 'approval'],
    uxPrimaryThemeId: 'ai_assisted_decision_experience',
    uxPrimarySubthemeId: 'human_approval_checkpoints',
    roadmapWaveId: 'wave_12_approval_foundation',
    acceptanceContractId: 'ui-library-wave-12-approval-foundation-v1',
    importStatement: "import { DecisionActionDialog } from '@mfe/design-system';",
    whereUsed: [],
    dependsOn: [
      'Dialog',
      'Button',
      'Textarea',
      'Select',
      'Checkbox',
      'Badge',
      'Text',
      'AssigneePicker',
    ],
  },
  apiItem: {
    name: 'DecisionActionDialog',
    variantAxes: [
      'mode: approve | reject | delegate | request_changes | attest',
      'size: sm | md | lg | xl | full',
    ],
    stateModel: [
      'reason text',
      'preset reason code (reject)',
      'delegate target (delegate)',
      'attestation accepted (attest)',
    ],
    previewStates: [
      'approve-default',
      'reject-required-reason',
      'delegate-actor-required',
      'request_changes-required-reason',
      'attest-checkbox-required',
      'busy-state',
    ],
    behaviorModel: [
      'Discriminated payload by `action`',
      'Reset state on open transitions',
      'Confirm disabled until mode-specific validity',
      'Attest payload populates DecisionAttestation { statement, acceptedAt }',
    ],
    props: [
      {
        name: 'open',
        type: 'boolean',
        default: '-',
        required: true,
        description: 'Diyalog goruntulenir mi.',
      },
      {
        name: 'mode',
        type: 'ApprovalAction',
        default: '-',
        required: true,
        description: 'Aksiyon kipi; dialog govdesi ve confirm fiili buna gore degisir.',
      },
      {
        name: 'requestSummary',
        type: '{ title, target, type }',
        default: '-',
        required: true,
        description: "Header'da gosterilen istek ozeti.",
      },
      {
        name: 'presetReasons',
        type: 'DecisionActionPresetReason[]',
        default: '[]',
        required: false,
        description: 'Reject kipinde gosterilen onceden tanimli gerekce listesi.',
      },
      {
        name: 'candidates',
        type: 'ApprovalActor[]',
        default: '[]',
        required: false,
        description: 'Delegate kipinde gerekli aday havuzu.',
      },
      {
        name: 'excludeIds',
        type: 'string[]',
        default: '[]',
        required: false,
        description: "Delegate kipinde adaydan dislanan id'ler (4-eyes).",
      },
      {
        name: 'attestationStatement',
        type: 'string',
        default: '-',
        required: false,
        description: 'Attest kipinde gosterilen ve kabul edilen beyan metni.',
      },
      {
        name: 'onConfirm',
        type: '(payload: DecisionActionConfirmPayload) => void',
        default: '-',
        required: true,
        description: 'Onay aksiyonunu discriminated payload ile yayar.',
      },
      {
        name: 'onCancel',
        type: '() => void',
        default: '-',
        required: true,
        description: "Iptal / kapatma callback'i.",
      },
      {
        name: 'busy',
        type: 'boolean',
        default: 'false',
        required: false,
        description: "Async aksiyon sirasinda confirm'i disable eder.",
      },
      {
        name: 'size',
        type: 'DialogSize',
        default: 'md',
        required: false,
        description: 'Diyalog boyut varyanti.',
      },
    ],
    previewFocus: [
      'mode-specific validation',
      'attest payload completeness',
      'preset reject reason wiring',
    ],
    regressionFocus: [
      'State reset on open re-transition',
      'Busy state guards confirm',
      'Discriminated payload action field',
    ],
  },
};

export default entry;
