import type { DesignLabComponentDocEntry } from '../types';

const entry: DesignLabComponentDocEntry = {
  name: 'ShellSidebar',
  indexItem: {
    name: 'ShellSidebar',
    kind: 'component',
    availability: 'exported',
    lifecycle: 'stable',
    maturity: 'beta',
    group: 'navigation',
    subgroup: 'sidebar',
    taxonomyGroupId: 'navigation',
    taxonomySubgroup: 'Navigation menu / side nav',
    demoMode: 'live',
    description:
      'Ready-made app shell sidebar pattern composing AppSidebar with branding header, command palette trigger, navigation items, folders submenu, footer actions, fullscreen toggle, and status indicator. Syncs width via CSS variable for layout coordination.',
    sectionIds: [
      'component_library_management',
      'navigation_patterns',
      'accessibility_compliance',
    ],
    qualityGates: [
      'design_tokens',
      'preview_visibility',
      'registry_export_sync',
      'ux_catalog_alignment',
      'a11y_keyboard_support',
    ],
    tags: ['wave-2', 'navigation', 'sidebar', 'pattern', 'beta', 'shell'],
    uxPrimaryThemeId: 'navigation_information_scent',
    uxPrimarySubthemeId: 'orientation_and_wayfinding',
    roadmapWaveId: 'wave_2_navigation',
    importStatement: "import { ShellSidebar } from '@mfe/design-system';",
    whereUsed: [],
    dependsOn: [
      'AppSidebar',
      'CommandPaletteTrigger',
      'FullscreenToggle',
      'StatusIndicator',
    ],
  },
  apiItem: {
    name: 'ShellSidebar',
    variantAxes: [
      'mode: expanded | collapsed (inherited from AppSidebar)',
    ],
    previewStates: [
      'default',
      'collapsed',
      'with-search',
      'with-folders',
      'with-status',
      'with-footer-actions',
      'dark-theme',
    ],
    behaviorModel: [
      'composes AppSidebar as root with all persistence/responsive behavior',
      'header: brand logo + title + subtitle + collapse trigger',
      'command palette trigger with compact mode in collapsed state',
      'navigation items mapped to AppSidebar.NavItem with active state',
      'collapsible folders group — auto-expands sidebar if clicked while collapsed',
      'footer: configurable actions + fullscreen toggle + status indicator',
      'CSS variable sync via MutationObserver on aside width for layout coordination',
      'renderFooter slot for custom content below default footer',
    ],
    props: [
      { name: 'navItems', type: 'ShellSidebarNavItem[]', default: '-', required: true, description: 'Navigation destinations.' },
      { name: 'activeKey', type: 'string', default: '-', required: false, description: 'Currently active nav item key.' },
      { name: 'onNavigate', type: '(key, item) => void', default: '-', required: false, description: 'Navigation callback.' },
      { name: 'brandTitle', type: 'string', default: '-', required: false, description: 'Brand title in header.' },
      { name: 'brandSubtitle', type: 'string', default: '-', required: false, description: 'Subtitle below brand title.' },
      { name: 'brandLogo', type: 'ReactNode', default: '-', required: false, description: 'Logo element in header.' },
      { name: 'onSearch', type: '() => void', default: '-', required: false, description: 'Command palette trigger callback.' },
      { name: 'searchShortcut', type: 'string', default: '-', required: false, description: 'Shortcut hint (e.g. "Ctrl+K").' },
      { name: 'folderItems', type: 'ShellSidebarFolderItem[]', default: '-', required: false, description: 'Folder submenu items.' },
      { name: 'footerActions', type: 'ShellSidebarFooterActionItem[]', default: '-', required: false, description: 'Footer action buttons.' },
      { name: 'statusIndicator', type: 'ShellSidebarStatusConfig', default: '-', required: false, description: 'Status indicator config.' },
      { name: 'storageKey', type: 'string', default: '-', required: false, description: 'localStorage key for state persistence.' },
      { name: 'cssWidthVar', type: 'string', default: '-', required: false, description: 'CSS variable set on documentElement for layout sync.' },
      { name: 'renderFooter', type: '(ctx) => ReactNode', default: '-', required: false, description: 'Custom footer content slot.' },
    ],
    previewFocus: [
      'full shell with all sections',
      'collapsed with icon-only nav + compact search',
      'folders expand/collapse behavior',
      'footer actions + fullscreen + status',
      'CSS variable sync with layout',
      'dark theme rendering',
    ],
    regressionFocus: [
      'auto-expand sidebar when folders clicked in collapsed mode',
      'CSS variable updates on mode change',
      'MutationObserver cleanup on unmount',
      'nav item active state matches activeKey',
      'collapsed tooltip on all interactive items',
      'dark mode token resolution across all sub-components',
    ],
  },
};

export default entry;
