import type { DesignLabApiCatalogMeta, DesignLabComponentDocEntry } from './types';
import entry1 from "./entries/AIActionAuditTimeline.doc";
import entry2 from "./entries/AIGuidedAuthoring.doc";
import entry3 from "./entries/AgGridServer.doc";
import entry4 from "./entries/AnchorToc.doc";
import entry5 from "./entries/ApprovalCheckpoint.doc";
import entry6 from "./entries/ApprovalReview.doc";
import entry7 from "./entries/Avatar.doc";
import entry8 from "./entries/Badge.doc";
import entry9 from "./entries/Breadcrumb.doc";
import entry10 from "./entries/Button.doc";
import entry11 from "./entries/Checkbox.doc";
import entry12 from "./entries/CitationPanel.doc";
import entry13 from "./entries/CommandPalette.doc";
import entry14 from "./entries/ConfidenceBadge.doc";
import entry15 from "./entries/ContextMenu.doc";
import entry16 from "./entries/DatePicker.doc";
import entry17 from "./entries/Descriptions.doc";
import entry18 from "./entries/DetailDrawer.doc";
import entry19 from "./entries/DetailSummary.doc";
import entry20 from "./entries/Divider.doc";
import entry21 from "./entries/Dropdown.doc";
import entry22 from "./entries/Empty.doc";
import entry23 from "./entries/EmptyErrorLoading.doc";
import entry24 from "./entries/EntityGridTemplate.doc";
import entry25 from "./entries/EntitySummaryBlock.doc";
import entry26 from "./entries/FilterBar.doc";
import entry27 from "./entries/FormDrawer.doc";
import entry28 from "./entries/IconButton.doc";
import entry29 from "./entries/JsonViewer.doc";
import entry30 from "./entries/LinkInline.doc";
import entry31 from "./entries/List.doc";
import entry32 from "./entries/Modal.doc";
import entry33 from "./entries/PageHeader.doc";
import entry34 from "./entries/PageLayout.doc";
import entry35 from "./entries/Pagination.doc";
import entry36 from "./entries/Popover.doc";
import entry37 from "./entries/PromptComposer.doc";
import entry38 from "./entries/Radio.doc";
import entry39 from "./entries/RecommendationCard.doc";
import entry40 from "./entries/ReportFilterPanel.doc";
import entry41 from "./entries/SearchFilterListing.doc";
import entry42 from "./entries/Select.doc";
import entry43 from "./entries/Skeleton.doc";
import entry44 from "./entries/Slider.doc";
import entry45 from "./entries/Spinner.doc";
import entry46 from "./entries/Steps.doc";
import entry47 from "./entries/SummaryStrip.doc";
import entry48 from "./entries/Switch.doc";
import entry49 from "./entries/THEME_APPEARANCE_OPTIONS.doc";
import entry50 from "./entries/THEME_DENSITY_OPTIONS.doc";
import entry51 from "./entries/THEME_ELEVATION_OPTIONS.doc";
import entry52 from "./entries/THEME_MOTION_OPTIONS.doc";
import entry53 from "./entries/THEME_RADIUS_OPTIONS.doc";
import entry54 from "./entries/TableSimple.doc";
import entry55 from "./entries/Tabs.doc";
import entry56 from "./entries/Tag.doc";
import entry57 from "./entries/Text.doc";
import entry58 from "./entries/TextArea.doc";
import entry59 from "./entries/TextInput.doc";
import entry60 from "./entries/ThemePresetCompare.doc";
import entry61 from "./entries/ThemePresetGallery.doc";
import entry62 from "./entries/ThemePreviewCard.doc";
import entry63 from "./entries/TimePicker.doc";
import entry64 from "./entries/Tooltip.doc";
import entry65 from "./entries/TourCoachmarks.doc";
import entry66 from "./entries/Tree.doc";
import entry67 from "./entries/TreeTable.doc";
import entry68 from "./entries/Upload.doc";
import entry69 from "./entries/buildAuthHeaders.doc";
import entry70 from "./entries/buildEntityGridQueryParams.doc";
import entry71 from "./entries/getResolvedToken.doc";
import entry72 from "./entries/getThemeAxes.doc";
import entry73 from "./entries/getThemeContract.doc";
import entry74 from "./entries/registerTokenResolver.doc";
import entry75 from "./entries/resetTokenResolver.doc";
import entry76 from "./entries/resolveAccessState.doc";
import entry77 from "./entries/resolveThemeModeKey.doc";
import entry78 from "./entries/setAppearance.doc";
import entry79 from "./entries/setDensity.doc";
import entry80 from "./entries/setElevation.doc";
import entry81 from "./entries/setMotion.doc";
import entry82 from "./entries/setOverlayIntensity.doc";
import entry83 from "./entries/setOverlayOpacity.doc";
import entry84 from "./entries/setRadius.doc";
import entry85 from "./entries/setSurfaceTone.doc";
import entry86 from "./entries/setTableSurfaceTone.doc";
import entry87 from "./entries/shouldBlockInteraction.doc";
import entry88 from "./entries/subscribeThemeAxes.doc";
import entry89 from "./entries/toggleVariantDefault.doc";
import entry90 from "./entries/updateThemeAxes.doc";
import entry91 from "./entries/useGridVariants.doc";
import entry92 from "./entries/withAccessGuard.doc";

export const designLabComponentDocEntries: DesignLabComponentDocEntry[] = [entry1, entry2, entry3, entry4, entry5, entry6, entry7, entry8, entry9, entry10, entry11, entry12, entry13, entry14, entry15, entry16, entry17, entry18, entry19, entry20, entry21, entry22, entry23, entry24, entry25, entry26, entry27, entry28, entry29, entry30, entry31, entry32, entry33, entry34, entry35, entry36, entry37, entry38, entry39, entry40, entry41, entry42, entry43, entry44, entry45, entry46, entry47, entry48, entry49, entry50, entry51, entry52, entry53, entry54, entry55, entry56, entry57, entry58, entry59, entry60, entry61, entry62, entry63, entry64, entry65, entry66, entry67, entry68, entry69, entry70, entry71, entry72, entry73, entry74, entry75, entry76, entry77, entry78, entry79, entry80, entry81, entry82, entry83, entry84, entry85, entry86, entry87, entry88, entry89, entry90, entry91, entry92];

export const designLabIndexItems = designLabComponentDocEntries.map((entry) => entry.indexItem);
export const designLabApiItems = designLabComponentDocEntries.flatMap((entry) => (entry.apiItem ? [entry.apiItem] : []));
export const designLabComponentDocMap = new Map(
  designLabComponentDocEntries.map((entry) => [entry.name, entry] as const),
);
export const designLabApiCatalogMeta: DesignLabApiCatalogMeta = {
  "version": "1.0",
  "subject_id": "ui_kutuphane_sistemi",
  "wave_id": "multi_wave_ui_library_catalog"
};
