export const PERMISSIONS = {
  USER_MANAGEMENT_MODULE: 'VIEW_USERS',
  USER_MANAGEMENT_EDIT: 'MANAGE_USERS',
  USER_MANAGEMENT_RESET_PASSWORD: 'MANAGE_USERS',
  USER_MANAGEMENT_TOGGLE_STATUS: 'MANAGE_USERS',
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;
