import React from "react";
import * as _MfeUiKit from "@mfe/design-system";

/**
 * Default props part 3: Templates, page compositions, MenuBar/NavigationMenu aliases
 */
export const DEFAULT_PROPS_TEMPLATES: Record<string, Record<string, unknown>> = {
  /* ---- Template components ---- */
  ActionBar: {
    items: [
      { value: "export", label: "Disa Aktar", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F4E4}") },
      { value: "archive", label: "Arsivle", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F4E6}") },
      { value: "delete", label: "Sil", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F5D1}\u{FE0F}") },
    ],
    size: "sm" as const,
    appearance: "ghost" as const,
    ariaLabel: "Toplu islem cubugu",
    startSlot: React.createElement("span", { className: "text-xs font-medium text-[var(--text-secondary)]" }, "3 oge secildi"),
  },
  SectionTabs: {
    tabs: [
      { id: "general", label: "Genel", description: "Temel yapilandirma" },
      { id: "advanced", label: "Gelismis", description: "Gelismis ayarlar" },
      { id: "debug", label: "Hata Ayiklama", description: "Hata ayiklama secenekleri" },
    ],
    activeTabId: "general",
    onTabChange: () => {},
  },

  /* ---- Page template compositions (alias → PageLayout) ---- */
  "CRUD Template": {
    title: "Kullanici Yonetimi",
    description: "Organizasyondaki kullanicilar, roller ve izinleri yonetin.",
    pageWidth: "wide" as const,
    breadcrumbItems: [
      { label: "Yonetim", href: "#" },
      { label: "Kullanicilar" },
    ],
    children: React.createElement("div", { className: "flex flex-col gap-4" },
      React.createElement("div", { className: "flex items-center justify-between rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-3" },
        React.createElement("div", { className: "flex items-center gap-3" },
          React.createElement("input", { className: "rounded-lg border border-[var(--border-subtle)] bg-transparent px-3 py-1.5 text-sm", placeholder: "Kullanici ara...", readOnly: true }),
          React.createElement("span", { className: "rounded-full bg-[var(--surface-muted)] px-3 py-1 text-xs" }, "Rol: Tumu"),
          React.createElement("span", { className: "rounded-full bg-[var(--surface-muted)] px-3 py-1 text-xs" }, "Durum: Aktif"),
        ),
        React.createElement("button", { className: "rounded-lg bg-[var(--action-primary))] px-4 py-1.5 text-xs font-medium text-text-inverse" }, "+ Kullanici Ekle"),
      ),
      React.createElement("div", { className: "grid grid-cols-4 gap-3" },
        React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-3 text-center" },
          React.createElement("div", { className: "text-xl font-bold text-[var(--text-primary)]" }, "1.248"),
          React.createElement("div", { className: "text-xs text-[var(--text-secondary)]" }, "Toplam Kullanici"),
        ),
        React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-3 text-center" },
          React.createElement("div", { className: "text-xl font-bold text-[var(--status-success))]" }, "1.102"),
          React.createElement("div", { className: "text-xs text-[var(--text-secondary)]" }, "Aktif"),
        ),
        React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-3 text-center" },
          React.createElement("div", { className: "text-xl font-bold text-[var(--status-warning))]" }, "98"),
          React.createElement("div", { className: "text-xs text-[var(--text-secondary)]" }, "Beklemede"),
        ),
        React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-3 text-center" },
          React.createElement("div", { className: "text-xl font-bold text-[var(--text-secondary)]" }, "48"),
          React.createElement("div", { className: "text-xs text-[var(--text-secondary)]" }, "Devre Disi"),
        ),
      ),
      React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] overflow-hidden" },
        React.createElement("table", { className: "w-full text-sm" },
          React.createElement("thead", null,
            React.createElement("tr", { className: "border-b border-[var(--border-subtle)] bg-[var(--surface-muted)]" },
              React.createElement("th", { className: "px-4 py-2 text-left text-xs font-medium text-[var(--text-secondary)]" }, "Ad Soyad"),
              React.createElement("th", { className: "px-4 py-2 text-left text-xs font-medium text-[var(--text-secondary)]" }, "E-posta"),
              React.createElement("th", { className: "px-4 py-2 text-left text-xs font-medium text-[var(--text-secondary)]" }, "Rol"),
              React.createElement("th", { className: "px-4 py-2 text-left text-xs font-medium text-[var(--text-secondary)]" }, "Durum"),
            ),
          ),
          React.createElement("tbody", null,
            React.createElement("tr", { className: "border-b border-[var(--border-subtle)]" },
              React.createElement("td", { className: "px-4 py-2.5 font-medium" }, "Ayse Demir"),
              React.createElement("td", { className: "px-4 py-2.5 text-[var(--text-secondary)]" }, "ayse@sirket.com"),
              React.createElement("td", { className: "px-4 py-2.5" }, React.createElement("span", { className: "rounded-full bg-[var(--surface-muted)] px-2 py-0.5 text-xs" }, "Yonetici")),
              React.createElement("td", { className: "px-4 py-2.5" }, React.createElement("span", { className: "inline-block h-2 w-2 rounded-full bg-[var(--status-success))]" }), " Aktif"),
            ),
            React.createElement("tr", { className: "border-b border-[var(--border-subtle)]" },
              React.createElement("td", { className: "px-4 py-2.5 font-medium" }, "Mehmet Kaya"),
              React.createElement("td", { className: "px-4 py-2.5 text-[var(--text-secondary)]" }, "mehmet@sirket.com"),
              React.createElement("td", { className: "px-4 py-2.5" }, React.createElement("span", { className: "rounded-full bg-[var(--surface-muted)] px-2 py-0.5 text-xs" }, "Duzenleyici")),
              React.createElement("td", { className: "px-4 py-2.5" }, React.createElement("span", { className: "inline-block h-2 w-2 rounded-full bg-[var(--status-success))]" }), " Aktif"),
            ),
            React.createElement("tr", null,
              React.createElement("td", { className: "px-4 py-2.5 font-medium" }, "Fatma Celik"),
              React.createElement("td", { className: "px-4 py-2.5 text-[var(--text-secondary)]" }, "fatma@sirket.com"),
              React.createElement("td", { className: "px-4 py-2.5" }, React.createElement("span", { className: "rounded-full bg-[var(--surface-muted)] px-2 py-0.5 text-xs" }, "Izleyici")),
              React.createElement("td", { className: "px-4 py-2.5" }, React.createElement("span", { className: "inline-block h-2 w-2 rounded-full bg-[var(--status-warning))]" }), " Beklemede"),
            ),
          ),
        ),
      ),
    ),
  },
  "Dashboard Template": {
    title: "Operasyon Panosu",
    description: "Temel performans metrikleri ve sistem sagligi genel gorunumu.",
    pageWidth: "wide" as const,
    breadcrumbItems: [
      { label: "Ana Sayfa", href: "#" },
      { label: "Pano" },
    ],
    children: React.createElement("div", { className: "flex flex-col gap-4" },
      React.createElement("div", { className: "grid grid-cols-4 gap-3" },
        React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-4" },
          React.createElement("div", { className: "text-xs font-medium uppercase tracking-wider text-[var(--text-secondary)]" }, "Gelir"),
          React.createElement("div", { className: "mt-1 text-2xl font-bold text-[var(--text-primary)]" }, "\u20BA1.24M"),
          React.createElement("div", { className: "mt-1 text-xs text-[var(--status-success))]" }, "\u2191 %12.3 gecen aya gore"),
        ),
        React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-4" },
          React.createElement("div", { className: "text-xs font-medium uppercase tracking-wider text-[var(--text-secondary)]" }, "Aktif Kullanici"),
          React.createElement("div", { className: "mt-1 text-2xl font-bold text-[var(--text-primary)]" }, "8.432"),
          React.createElement("div", { className: "mt-1 text-xs text-[var(--status-success))]" }, "\u2191 %5.7 gecen aya gore"),
        ),
        React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-4" },
          React.createElement("div", { className: "text-xs font-medium uppercase tracking-wider text-[var(--text-secondary)]" }, "Calisma Suresi"),
          React.createElement("div", { className: "mt-1 text-2xl font-bold text-[var(--status-success))]" }, "%99.97"),
          React.createElement("div", { className: "mt-1 text-xs text-[var(--text-secondary)]" }, "Son 30 gun"),
        ),
        React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-4" },
          React.createElement("div", { className: "text-xs font-medium uppercase tracking-wider text-[var(--text-secondary)]" }, "Acik Talepler"),
          React.createElement("div", { className: "mt-1 text-2xl font-bold text-[var(--status-warning))]" }, "23"),
          React.createElement("div", { className: "mt-1 text-xs text-[var(--status-error))]" }, "\u2191 3 dunden beri"),
        ),
      ),
      React.createElement("div", { className: "grid grid-cols-2 gap-4" },
        React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-4" },
          React.createElement("div", { className: "mb-3 text-sm font-semibold text-[var(--text-primary)]" }, "Son Etkinlik"),
          React.createElement("div", { className: "flex flex-col gap-2" },
            React.createElement("div", { className: "flex items-center justify-between rounded-lg bg-[var(--surface-muted)] px-3 py-2 text-xs" },
              React.createElement("span", null, "v2.4.1 dagitimi tamamlandi"),
              React.createElement("span", { className: "text-[var(--text-secondary)]" }, "2 dk once"),
            ),
            React.createElement("div", { className: "flex items-center justify-between rounded-lg bg-[var(--surface-muted)] px-3 py-2 text-xs" },
              React.createElement("span", null, "Yeni kullanici kayit artisi tespit edildi"),
              React.createElement("span", { className: "text-[var(--text-secondary)]" }, "15 dk once"),
            ),
            React.createElement("div", { className: "flex items-center justify-between rounded-lg bg-[var(--surface-muted)] px-3 py-2 text-xs" },
              React.createElement("span", null, "Veritabani yedeklemesi tamamlandi"),
              React.createElement("span", { className: "text-[var(--text-secondary)]" }, "1 saat once"),
            ),
          ),
        ),
        React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-4" },
          React.createElement("div", { className: "mb-3 text-sm font-semibold text-[var(--text-primary)]" }, "Sistem Sagligi"),
          React.createElement("div", { className: "flex flex-col gap-3" },
            React.createElement("div", null,
              React.createElement("div", { className: "flex justify-between text-xs mb-1" }, React.createElement("span", null, "API Sunucusu"), React.createElement("span", { className: "text-[var(--status-success))]" }, "Saglikli")),
              React.createElement("div", { className: "h-2 rounded-full bg-[var(--surface-muted)]" }, React.createElement("div", { className: "h-2 rounded-full bg-[var(--status-success))]", style: { width: "99%" } })),
            ),
            React.createElement("div", null,
              React.createElement("div", { className: "flex justify-between text-xs mb-1" }, React.createElement("span", null, "Veritabani"), React.createElement("span", { className: "text-[var(--status-success))]" }, "Saglikli")),
              React.createElement("div", { className: "h-2 rounded-full bg-[var(--surface-muted)]" }, React.createElement("div", { className: "h-2 rounded-full bg-[var(--status-success))]", style: { width: "95%" } })),
            ),
            React.createElement("div", null,
              React.createElement("div", { className: "flex justify-between text-xs mb-1" }, React.createElement("span", null, "CDN"), React.createElement("span", { className: "text-[var(--status-warning))]" }, "Dusuk Performans")),
              React.createElement("div", { className: "h-2 rounded-full bg-[var(--surface-muted)]" }, React.createElement("div", { className: "h-2 rounded-full bg-[var(--status-warning))]", style: { width: "78%" } })),
            ),
          ),
        ),
      ),
    ),
  },
  "Detail Template": {
    title: "Siparis #SIP-2024-1847",
    description: "Varlik ozeti ve meta verilerle siparis detay gorunumu.",
    breadcrumbItems: [
      { label: "Siparisler", href: "#" },
      { label: "#SIP-2024-1847" },
    ],
    children: React.createElement("div", { className: "flex flex-col gap-4" },
      React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-4" },
        React.createElement("div", { className: "flex items-center justify-between mb-3" },
          React.createElement("div", null,
            React.createElement("div", { className: "text-base font-semibold text-[var(--text-primary)]" }, "Acme Teknoloji A.S."),
            React.createElement("div", { className: "text-sm text-[var(--text-secondary)]" }, "Kurumsal Musteri \u2014 Istanbul, TR"),
          ),
          React.createElement("span", { className: "rounded-full bg-[color-mix(in_oklab,var(--status-success))_10%,transparent)] px-3 py-1 text-xs font-medium text-[var(--status-success))]" }, "Teslim Edildi"),
        ),
        React.createElement("div", { className: "grid grid-cols-3 gap-4 text-sm" },
          React.createElement("div", null, React.createElement("span", { className: "text-xs text-[var(--text-secondary)]" }, "Siparis Tarihi"), React.createElement("div", { className: "font-medium" }, "2024-03-15")),
          React.createElement("div", null, React.createElement("span", { className: "text-xs text-[var(--text-secondary)]" }, "Toplam Tutar"), React.createElement("div", { className: "font-medium" }, "\u20BA45.200,00")),
          React.createElement("div", null, React.createElement("span", { className: "text-xs text-[var(--text-secondary)]" }, "Odeme"), React.createElement("div", { className: "font-medium" }, "Havale/EFT")),
        ),
      ),
      React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-4" },
        React.createElement("div", { className: "text-sm font-semibold text-[var(--text-primary)] mb-3" }, "Kalemler"),
        React.createElement("div", { className: "flex flex-col gap-2" },
          React.createElement("div", { className: "flex items-center justify-between rounded-lg bg-[var(--surface-muted)] px-3 py-2 text-xs" },
            React.createElement("span", { className: "font-medium" }, "Kurumsal Lisans (Yillik)"),
            React.createElement("span", null, "1 x \u20BA35.000,00"),
          ),
          React.createElement("div", { className: "flex items-center justify-between rounded-lg bg-[var(--surface-muted)] px-3 py-2 text-xs" },
            React.createElement("span", { className: "font-medium" }, "Premium Destek"),
            React.createElement("span", null, "1 x \u20BA10.200,00"),
          ),
        ),
      ),
    ),
    detail: React.createElement("div", { className: "flex flex-col gap-3 p-3" },
      React.createElement("div", { className: "text-xs font-semibold text-[var(--text-secondary)] uppercase tracking-wider" }, "Zaman Cizelgesi"),
      React.createElement("div", { className: "flex flex-col gap-2" },
        React.createElement("div", { className: "flex gap-2 text-xs" },
          React.createElement("span", { className: "text-[var(--text-secondary)]" }, "Mar 15"),
          React.createElement("span", null, "Siparis olusturuldu"),
        ),
        React.createElement("div", { className: "flex gap-2 text-xs" },
          React.createElement("span", { className: "text-[var(--text-secondary)]" }, "Mar 16"),
          React.createElement("span", null, "Odeme alindi"),
        ),
        React.createElement("div", { className: "flex gap-2 text-xs" },
          React.createElement("span", { className: "text-[var(--text-secondary)]" }, "Mar 17"),
          React.createElement("span", null, "Lisans aktiflestirildi"),
        ),
      ),
    ),
  },
  "Settings Template": {
    title: "Organizasyon Ayarlari",
    description: "Organizasyon tercihleri, guvenlik ve bildirim politikalarini yapilandirin.",
    stickyHeader: true,
    breadcrumbItems: [
      { label: "Yonetim", href: "#" },
      { label: "Ayarlar" },
    ],
    children: React.createElement("div", { className: "flex flex-col gap-4" },
      React.createElement("div", { className: "flex gap-4 border-b border-[var(--border-subtle)] pb-2 text-sm" },
        React.createElement("span", { className: "border-b-2 border-[var(--action-primary))] pb-2 font-medium text-[var(--action-primary))]" }, "Genel"),
        React.createElement("span", { className: "pb-2 text-[var(--text-secondary)] cursor-pointer" }, "Guvenlik"),
        React.createElement("span", { className: "pb-2 text-[var(--text-secondary)] cursor-pointer" }, "Bildirimler"),
        React.createElement("span", { className: "pb-2 text-[var(--text-secondary)] cursor-pointer" }, "Entegrasyonlar"),
      ),
      React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-4" },
        React.createElement("div", { className: "text-sm font-semibold text-[var(--text-primary)] mb-4" }, "Organizasyon Profili"),
        React.createElement("div", { className: "flex flex-col gap-3" },
          React.createElement("div", { className: "flex items-center justify-between" },
            React.createElement("div", null,
              React.createElement("div", { className: "text-sm font-medium" }, "Organizasyon Adi"),
              React.createElement("div", { className: "text-xs text-[var(--text-secondary)]" }, "Acme Teknoloji A.S."),
            ),
            React.createElement("button", { className: "rounded-lg border border-[var(--border-subtle)] px-3 py-1 text-xs" }, "Duzenle"),
          ),
          React.createElement("div", { className: "border-t border-[var(--border-subtle)] pt-3 flex items-center justify-between" },
            React.createElement("div", null,
              React.createElement("div", { className: "text-sm font-medium" }, "Varsayilan Saat Dilimi"),
              React.createElement("div", { className: "text-xs text-[var(--text-secondary)]" }, "Europe/Istanbul (UTC+3)"),
            ),
            React.createElement("button", { className: "rounded-lg border border-[var(--border-subtle)] px-3 py-1 text-xs" }, "Duzenle"),
          ),
          React.createElement("div", { className: "border-t border-[var(--border-subtle)] pt-3 flex items-center justify-between" },
            React.createElement("div", null,
              React.createElement("div", { className: "text-sm font-medium" }, "Iki Faktorlu Dogrulama"),
              React.createElement("div", { className: "text-xs text-[var(--text-secondary)]" }, "Tum yonetici kullanicilar icin zorunlu"),
            ),
            React.createElement("div", { className: "h-5 w-9 rounded-full bg-[var(--status-success))] relative" },
              React.createElement("div", { className: "absolute right-0.5 top-0.5 h-4 w-4 rounded-full bg-[var(--surface-default))] shadow-xs" }),
            ),
          ),
        ),
      ),
    ),
  },
  "Command Workspace": {
    title: "Komut Merkezi",
    description: "Birlesik calisma alanindan arama yapin, son calismalara gozatin ve islemleri yurutun.",
    pageWidth: "wide" as const,
    stickyHeader: true,
    breadcrumbItems: [
      { label: "Calisma Alani", href: "#" },
      { label: "Komutlar" },
    ],
    children: React.createElement("div", { className: "flex flex-col gap-4" },
      React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-3" },
        React.createElement("div", { className: "flex items-center gap-2 rounded-lg bg-[var(--surface-muted)] px-3 py-2" },
          React.createElement("span", { className: "text-[var(--text-secondary)]" }, "\u{1F50D}"),
          React.createElement("span", { className: "text-sm text-[var(--text-secondary)]" }, "Komut, varlik veya islem ara..."),
          React.createElement("span", { className: "ml-auto rounded-xs border border-[var(--border-subtle)] bg-[var(--surface-default))] px-1.5 py-0.5 text-[10px] text-[var(--text-secondary)]" }, "⌘K"),
        ),
      ),
      React.createElement("div", { className: "grid grid-cols-2 gap-4" },
        React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-4" },
          React.createElement("div", { className: "mb-3 text-sm font-semibold text-[var(--text-primary)]" }, "Son Calismalar"),
          React.createElement("div", { className: "flex flex-col gap-2" },
            React.createElement("div", { className: "flex items-center gap-2 rounded-lg bg-[var(--surface-muted)] px-3 py-2 text-xs cursor-pointer" },
              React.createElement("span", { className: "rounded-xs bg-[color-mix(in_oklab,var(--action-primary))_10%,transparent)] px-1.5 py-0.5 text-[10px] font-medium text-[var(--action-primary))]" }, "SIPARIS"),
              React.createElement("span", { className: "font-medium" }, "#SIP-2024-1847"),
              React.createElement("span", { className: "ml-auto text-[var(--text-secondary)]" }, "2 dk once"),
            ),
            React.createElement("div", { className: "flex items-center gap-2 rounded-lg bg-[var(--surface-muted)] px-3 py-2 text-xs cursor-pointer" },
              React.createElement("span", { className: "rounded-xs bg-[color-mix(in_oklab,var(--status-success))_10%,transparent)] px-1.5 py-0.5 text-[10px] font-medium text-[var(--status-success))]" }, "KULLANICI"),
              React.createElement("span", { className: "font-medium" }, "Ayse Demir"),
              React.createElement("span", { className: "ml-auto text-[var(--text-secondary)]" }, "15 dk once"),
            ),
            React.createElement("div", { className: "flex items-center gap-2 rounded-lg bg-[var(--surface-muted)] px-3 py-2 text-xs cursor-pointer" },
              React.createElement("span", { className: "rounded-xs bg-[color-mix(in_oklab,var(--status-warning))_10%,transparent)] px-1.5 py-0.5 text-[10px] font-medium text-[var(--status-warning))]" }, "TALEP"),
              React.createElement("span", { className: "font-medium" }, "TLP-5523 CDN gecikmesi"),
              React.createElement("span", { className: "ml-auto text-[var(--text-secondary)]" }, "1 saat once"),
            ),
          ),
        ),
        React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-4" },
          React.createElement("div", { className: "mb-3 text-sm font-semibold text-[var(--text-primary)]" }, "Hizli Islemler"),
          React.createElement("div", { className: "grid grid-cols-2 gap-2" },
            React.createElement("button", { className: "rounded-lg border border-[var(--border-subtle)] px-3 py-2 text-xs text-left hover:bg-[var(--surface-muted)]" }, "Yeni Rapor"),
            React.createElement("button", { className: "rounded-lg border border-[var(--border-subtle)] px-3 py-2 text-xs text-left hover:bg-[var(--surface-muted)]" }, "Kullanici Ekle"),
            React.createElement("button", { className: "rounded-lg border border-[var(--border-subtle)] px-3 py-2 text-xs text-left hover:bg-[var(--surface-muted)]" }, "Dagitim Yap"),
            React.createElement("button", { className: "rounded-lg border border-[var(--border-subtle)] px-3 py-2 text-xs text-left hover:bg-[var(--surface-muted)]" }, "Veri Aktar"),
          ),
        ),
      ),
    ),
  },

  /* ---- MenuBar recipe aliases (no-space keys) ---- */
  ActionHeader: {
    items: [
      { value: "save", label: "Kaydet", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F4BE}") },
      { value: "discard", label: "Iptal", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{274C}") },
      { value: "publish", label: "Yayinla", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F680}") },
    ],
    size: "sm" as const,
    appearance: "ghost" as const,
    ariaLabel: "Islem basligi",
  },
  AppHeader: {
    items: [
      { value: "home", label: "Ana Sayfa", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F3E0}") },
      { value: "projects", label: "Projeler", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F4C1}") },
      { value: "team", label: "Ekip", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F465}") },
      { value: "settings", label: "Ayarlar", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{2699}\u{FE0F}") },
    ],
    value: "home",
    size: "md" as const,
    appearance: "default" as const,
    ariaLabel: "Uygulama basligi",
    startSlot: React.createElement("span", { className: "text-sm font-bold text-[var(--text-primary)]" }, "MFE Platform"),
  },
  CommandHeader: {
    items: [
      { value: "search", label: "Ara", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F50D}") },
      { value: "filter", label: "Filtrele", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F3AF}") },
      { value: "sort", label: "Sirala", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{2195}\u{FE0F}") },
    ],
    size: "sm" as const,
    appearance: "outline" as const,
    enableSearchHandoff: true,
    searchPlaceholder: "Komut ara...",
    ariaLabel: "Komut basligi",
  },
  DesktopMenubar: {
    items: [
      { value: "file", label: "Dosya", menuItems: [
        { value: "new", label: "Yeni" },
        { value: "open", label: "Ac" },
        { value: "save", label: "Kaydet" },
      ] },
      { value: "edit", label: "Duzenle", menuItems: [
        { value: "undo", label: "Geri Al" },
        { value: "redo", label: "Yinele" },
        { value: "cut", label: "Kes" },
        { value: "copy", label: "Kopyala" },
      ] },
      { value: "view", label: "Gorunum", menuItems: [
        { value: "zoom-in", label: "Yakinlastir" },
        { value: "zoom-out", label: "Uzaklastir" },
        { value: "fullscreen", label: "Tam Ekran" },
      ] },
      { value: "help", label: "Yardim" },
    ],
    size: "sm" as const,
    appearance: "ghost" as const,
    submenuTrigger: "hover" as const,
    ariaLabel: "Masaustu menu cubugu",
  },
  NavigationMenu: {
    items: [
      { value: "dashboard", label: "Kontrol Paneli", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F4CA}") },
      { value: "orders", label: "Siparisler", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F4E6}"), badge: React.createElement("span", { className: "rounded-full bg-[var(--status-error))] px-1.5 py-0.5 text-[10px] text-text-inverse" }, "3") },
      { value: "customers", label: "Musteriler", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F465}") },
      { value: "products", label: "Urunler", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F4E6}") },
      { value: "reports", label: "Raporlar", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F4C8}") },
    ],
    value: "dashboard",
    size: "md" as const,
    labelVisibility: "always" as const,
    ariaLabel: "Ana navigasyon menusu",
  },

  /* ---- Overlay components (missing entries) ---- */
  DetailDrawer: {
    open: true,
    title: "Siparis Detayi",
    subtitle: "#SIP-2024-0847",
    size: "lg" as const,
    disablePortal: true,
    onClose: () => {},
    sections: [
      {
        key: "overview",
        title: "Genel Bilgiler",
        content: React.createElement("div", { className: "flex flex-col gap-2 text-sm" },
          React.createElement("div", { className: "flex justify-between" },
            React.createElement("span", { className: "text-[var(--text-secondary)]" }, "Musteri"),
            React.createElement("span", { className: "font-medium" }, "Acme Teknoloji A.S."),
          ),
          React.createElement("div", { className: "flex justify-between" },
            React.createElement("span", { className: "text-[var(--text-secondary)]" }, "Tarih"),
            React.createElement("span", { className: "font-medium" }, "2024-03-15"),
          ),
          React.createElement("div", { className: "flex justify-between" },
            React.createElement("span", { className: "text-[var(--text-secondary)]" }, "Tutar"),
            React.createElement("span", { className: "font-medium" }, "\u20BA45.200,00"),
          ),
          React.createElement("div", { className: "flex justify-between" },
            React.createElement("span", { className: "text-[var(--text-secondary)]" }, "Durum"),
            React.createElement("span", { className: "rounded-full bg-[color-mix(in_oklab,var(--status-success))_10%,transparent)] px-2 py-0.5 text-xs font-medium text-[var(--status-success))]" }, "Tamamlandi"),
          ),
        ),
      },
      {
        key: "items",
        title: "Kalemler",
        content: React.createElement("div", { className: "flex flex-col gap-2" },
          React.createElement("div", { className: "flex items-center justify-between rounded-lg bg-[var(--surface-muted)] px-3 py-2 text-xs" },
            React.createElement("span", { className: "font-medium" }, "Kurumsal Lisans (Yillik)"),
            React.createElement("span", null, "1 x ₺35.000,00"),
          ),
          React.createElement("div", { className: "flex items-center justify-between rounded-lg bg-[var(--surface-muted)] px-3 py-2 text-xs" },
            React.createElement("span", { className: "font-medium" }, "Premium Destek"),
            React.createElement("span", null, "1 x ₺10.200,00"),
          ),
        ),
      },
    ],
    tags: React.createElement("span", { className: "rounded-full bg-[color-mix(in_oklab,var(--status-success))_10%,transparent)] px-2 py-0.5 text-xs font-medium text-[var(--status-success))]" }, "Onaylandi"),
  },
  FormDrawer: {
    open: true,
    title: "Yeni Musteri Ekle",
    subtitle: "Musteri bilgilerini giriniz",
    size: "md" as const,
    placement: "right" as const,
    onClose: () => {},
    children: React.createElement("div", { className: "flex flex-col gap-4 p-4" },
      React.createElement("div", { className: "flex flex-col gap-1" },
        React.createElement("label", { className: "text-xs font-medium text-[var(--text-secondary)]" }, "Sirket Adi"),
        React.createElement("input", { className: "rounded-lg border border-[var(--border-subtle)] bg-transparent px-3 py-2 text-sm", placeholder: "ornek: Acme Teknoloji A.S.", readOnly: true }),
      ),
      React.createElement("div", { className: "flex flex-col gap-1" },
        React.createElement("label", { className: "text-xs font-medium text-[var(--text-secondary)]" }, "Yetkili Kisi"),
        React.createElement("input", { className: "rounded-lg border border-[var(--border-subtle)] bg-transparent px-3 py-2 text-sm", placeholder: "Ad Soyad", readOnly: true }),
      ),
      React.createElement("div", { className: "flex flex-col gap-1" },
        React.createElement("label", { className: "text-xs font-medium text-[var(--text-secondary)]" }, "E-posta"),
        React.createElement("input", { className: "rounded-lg border border-[var(--border-subtle)] bg-transparent px-3 py-2 text-sm", placeholder: "info@sirket.com", readOnly: true }),
      ),
      React.createElement("div", { className: "flex flex-col gap-1" },
        React.createElement("label", { className: "text-xs font-medium text-[var(--text-secondary)]" }, "Telefon"),
        React.createElement("input", { className: "rounded-lg border border-[var(--border-subtle)] bg-transparent px-3 py-2 text-sm", placeholder: "+90 212 555 0000", readOnly: true }),
      ),
    ),
    footer: React.createElement("div", { className: "flex justify-end gap-2 p-4 border-t border-[var(--border-subtle)]" },
      React.createElement("button", { className: "rounded-lg border border-[var(--border-subtle)] px-4 py-1.5 text-xs" }, "Iptal"),
      React.createElement("button", { className: "rounded-lg bg-[var(--action-primary))] px-4 py-1.5 text-xs font-medium text-text-inverse" }, "Kaydet"),
    ),
  },

  /* ---- Advanced data grids ---- */
  EntityGridTemplate: {
    gridId: "demo-entity-grid",
    gridSchemaVersion: 1,
    columnDefs: [
      { field: "name", headerName: "Ad Soyad", flex: 1 },
      { field: "department", headerName: "Departman", flex: 1 },
      { field: "role", headerName: "Rol", width: 150 },
      { field: "status", headerName: "Durum", width: 120 },
    ],
    rowData: [
      { name: "Ayse Demir", department: "Muhendislik", role: "Kidemli Gelistirici", status: "Aktif" },
      { name: "Mehmet Kaya", department: "Tasarim", role: "UX Tasarimci", status: "Aktif" },
      { name: "Fatma Celik", department: "Urun", role: "Urun Yoneticisi", status: "Izinli" },
      { name: "Ali Yildiz", department: "Muhendislik", role: "DevOps Muhendisi", status: "Aktif" },
    ],
    total: 4,
    page: 1,
    pageSize: 10,
    messages: {
      quickFilterPlaceholder: "Hizli filtre...",
      quickFilterLabel: "Hizli Filtre",
      variantLabel: "Gorunum",
      densityToggleLabel: "Yogunluk",
      comfortableDensityLabel: "Rahat",
      compactDensityLabel: "Kompakt",
      densityResetLabel: "Sifirla",
      fullscreenTooltip: "Tam ekran",
      resetFiltersLabel: "Filtreleri sifirla",
      overlayLoadingLabel: "Yukleniyor...",
      overlayNoRowsLabel: "Kayit bulunamadi",
      pageSizeLabel: "Sayfa basina:",
      recordCountLabel: "kayit",
      firstPageLabel: "Ilk sayfa",
      previousPageLabel: "Onceki",
      nextPageLabel: "Sonraki",
      lastPageLabel: "Son sayfa",
    },
  },
  AgGridServer: {
    columnDefs: [
      { field: "orderId", headerName: "Siparis No", width: 140 },
      { field: "customer", headerName: "Musteri", flex: 1 },
      { field: "total", headerName: "Tutar", width: 120 },
      { field: "status", headerName: "Durum", width: 120 },
    ],
    getData: () => Promise.resolve({
      rows: [
        { orderId: "SIP-001", customer: "Acme A.S.", total: "₺12.500", status: "Tamamlandi" },
        { orderId: "SIP-002", customer: "Beta Ltd.", total: "₺8.750", status: "Beklemede" },
        { orderId: "SIP-003", customer: "Gamma Holding", total: "₺23.100", status: "Kargoda" },
      ],
      total: 3,
    }),
    height: 300,
  },

};
