import React from "react";

/**
 * Default props part 4: Theme, Toast, alias keys, X-Suite component defaults
 */
export const DEFAULT_PROPS_THEME: Record<string, Record<string, unknown>> = {
  /* ---- Theme ---- */
  ThemePresetCompare: {
    title: "Tema Karsilastirmasi",
    description: "Iki tema presetini eksen bazinda karsilastirin.",
    leftPreset: {
      presetId: "light-default",
      label: "Acik Tema",
      appearance: "light",
      density: "comfortable",
      intent: "neutral",
      isHighContrast: false,
      isDefaultMode: true,
      themeMode: "light",
    },
    rightPreset: {
      presetId: "dark-compact",
      label: "Koyu Kompakt",
      appearance: "dark",
      density: "compact",
      intent: "branded",
      isHighContrast: true,
      isDefaultMode: false,
      themeMode: "dark",
    },
    axes: ["appearance", "density", "intent", "contrast"],
  },

  /* ---- Toast ---- */
  ToastProvider: {
    position: "top-right" as const,
    duration: 4000,
    maxVisible: 3,
    children: React.createElement("div", { className: "flex flex-col gap-3 p-4" },
      React.createElement("div", { className: "text-sm font-medium text-[var(--text-primary)]" }, "Toast Provider Demo"),
      React.createElement("div", { className: "text-xs text-[var(--text-secondary)]" }, "ToastProvider uygulamayi sarar ve useToast hook'u ile bildirim gostermeyi saglar."),
      React.createElement("div", { className: "flex gap-2 mt-3" },
        React.createElement("div", { className: "rounded-lg border border-[color-mix(in_oklab,var(--state-success-text)_20%,transparent)] bg-[var(--surface-default)] px-3 py-2 text-xs" },
          React.createElement("span", { className: "font-medium text-[var(--state-success-text)]" }, "Basarili: "),
          "Kayit basariyla eklendi.",
        ),
        React.createElement("div", { className: "rounded-lg border border-[color-mix(in_oklab,var(--state-info-text)_20%,transparent)] bg-[var(--surface-default)] px-3 py-2 text-xs" },
          React.createElement("span", { className: "font-medium text-[var(--state-info-text)]" }, "Bilgi: "),
          "Yeni guncelleme mevcut.",
        ),
      ),
    ),
  },

  /* ---- Space-separated MenuBar alias keys (point to their PascalCase variants) ---- */
  "App Header": {
    items: [
      { value: "home", label: "Ana Sayfa", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F3E0}") },
      { value: "projects", label: "Projeler", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F4C1}") },
      { value: "team", label: "Ekip", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F465}") },
      { value: "settings", label: "Ayarlar", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{2699}\u{FE0F}") },
    ],
    value: "home",
    size: "md" as const,
    appearance: "default" as const,
    ariaLabel: "Uygulama basligi",
    startSlot: React.createElement("span", { className: "text-sm font-bold text-[var(--text-primary)]" }, "MFE Platform"),
  },
  "Search / Command Header": {
    items: [
      { value: "search", label: "Ara", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F50D}") },
      { value: "filter", label: "Filtrele", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F3AF}") },
      { value: "sort", label: "Sirala", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{2195}\u{FE0F}") },
    ],
    size: "sm" as const,
    appearance: "outline" as const,
    enableSearchHandoff: true,
    searchPlaceholder: "Komut ara...",
    ariaLabel: "Komut basligi",
  },
  "Action Header": {
    items: [
      { value: "save", label: "Kaydet", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F4BE}") },
      { value: "discard", label: "Iptal", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{274C}") },
      { value: "publish", label: "Yayinla", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F680}") },
    ],
    size: "sm" as const,
    appearance: "ghost" as const,
    ariaLabel: "Islem basligi",
  },
  "Action Bar": {
    items: [
      { value: "export", label: "Disa Aktar", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F4E4}") },
      { value: "archive", label: "Arsivle", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F4E6}") },
      { value: "delete", label: "Sil", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F5D1}\u{FE0F}") },
    ],
    size: "sm" as const,
    appearance: "ghost" as const,
    ariaLabel: "Toplu islem cubugu",
    startSlot: React.createElement("span", { className: "text-xs font-medium text-[var(--text-secondary)]" }, "3 oge secildi"),
  },
  "Navigation Menu": {
    items: [
      { value: "dashboard", label: "Kontrol Paneli", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F4CA}") },
      { value: "orders", label: "Siparisler", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F4E6}"), badge: React.createElement("span", { className: "rounded-full bg-[var(--status-error))] px-1.5 py-0.5 text-[10px] text-text-inverse" }, "3") },
      { value: "customers", label: "Musteriler", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F465}") },
      { value: "products", label: "Urunler", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F4E6}") },
      { value: "reports", label: "Raporlar", icon: React.createElement("span", { style: { fontSize: 14 } }, "\u{1F4C8}") },
    ],
    value: "dashboard",
    size: "md" as const,
    labelVisibility: "always" as const,
    ariaLabel: "Ana navigasyon menusu",
  },
  "Desktop Menubar": {
    items: [
      { value: "file", label: "Dosya", menuItems: [
        { value: "new", label: "Yeni" },
        { value: "open", label: "Ac" },
        { value: "save", label: "Kaydet" },
      ] },
      { value: "edit", label: "Duzenle", menuItems: [
        { value: "undo", label: "Geri Al" },
        { value: "redo", label: "Yinele" },
        { value: "cut", label: "Kes" },
        { value: "copy", label: "Kopyala" },
      ] },
      { value: "view", label: "Gorunum", menuItems: [
        { value: "zoom-in", label: "Yakinlastir" },
        { value: "zoom-out", label: "Uzaklastir" },
        { value: "fullscreen", label: "Tam Ekran" },
      ] },
      { value: "help", label: "Yardim" },
    ],
    size: "sm" as const,
    appearance: "ghost" as const,
    submenuTrigger: "hover" as const,
    ariaLabel: "Masaustu menu cubugu",
  },

  /* ---- Non-space alias keys for templates (point to same PageLayout-based preview) ---- */
  CrudTemplate: {
    title: "Kullanici Yonetimi",
    description: "Organizasyondaki kullanicilar, roller ve izinleri yonetin.",
    pageWidth: "wide" as const,
    breadcrumbItems: [
      { label: "Yonetim", href: "#" },
      { label: "Kullanicilar" },
    ],
    children: React.createElement("div", { className: "flex flex-col gap-4" },
      React.createElement("div", { className: "flex items-center justify-between rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-3" },
        React.createElement("div", { className: "flex items-center gap-3" },
          React.createElement("input", { className: "rounded-lg border border-[var(--border-subtle)] bg-transparent px-3 py-1.5 text-sm", placeholder: "Kullanici ara...", readOnly: true }),
          React.createElement("span", { className: "rounded-full bg-[var(--surface-muted)] px-3 py-1 text-xs" }, "Rol: Tumu"),
          React.createElement("span", { className: "rounded-full bg-[var(--surface-muted)] px-3 py-1 text-xs" }, "Durum: Aktif"),
        ),
        React.createElement("button", { className: "rounded-lg bg-[var(--action-primary))] px-4 py-1.5 text-xs font-medium text-text-inverse" }, "+ Kullanici Ekle"),
      ),
      React.createElement("div", { className: "grid grid-cols-3 gap-3" },
        React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-3 text-center" },
          React.createElement("div", { className: "text-xl font-bold text-[var(--text-primary)]" }, "248"),
          React.createElement("div", { className: "text-xs text-[var(--text-secondary)]" }, "Toplam Kullanici"),
        ),
        React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-3 text-center" },
          React.createElement("div", { className: "text-xl font-bold text-[var(--status-success))]" }, "210"),
          React.createElement("div", { className: "text-xs text-[var(--text-secondary)]" }, "Aktif"),
        ),
        React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-3 text-center" },
          React.createElement("div", { className: "text-xl font-bold text-[var(--status-warning))]" }, "38"),
          React.createElement("div", { className: "text-xs text-[var(--text-secondary)]" }, "Beklemede"),
        ),
      ),
      React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] overflow-hidden" },
        React.createElement("table", { className: "w-full text-sm" },
          React.createElement("thead", null,
            React.createElement("tr", { className: "border-b border-[var(--border-subtle)] bg-[var(--surface-muted)]" },
              React.createElement("th", { className: "px-4 py-2 text-left text-xs font-medium text-[var(--text-secondary)]" }, "Ad Soyad"),
              React.createElement("th", { className: "px-4 py-2 text-left text-xs font-medium text-[var(--text-secondary)]" }, "E-posta"),
              React.createElement("th", { className: "px-4 py-2 text-left text-xs font-medium text-[var(--text-secondary)]" }, "Rol"),
            ),
          ),
          React.createElement("tbody", null,
            React.createElement("tr", { className: "border-b border-[var(--border-subtle)]" },
              React.createElement("td", { className: "px-4 py-2.5 font-medium" }, "Ayse Demir"),
              React.createElement("td", { className: "px-4 py-2.5 text-[var(--text-secondary)]" }, "ayse@sirket.com"),
              React.createElement("td", { className: "px-4 py-2.5" }, React.createElement("span", { className: "rounded-full bg-[var(--surface-muted)] px-2 py-0.5 text-xs" }, "Yonetici")),
            ),
            React.createElement("tr", null,
              React.createElement("td", { className: "px-4 py-2.5 font-medium" }, "Mehmet Kaya"),
              React.createElement("td", { className: "px-4 py-2.5 text-[var(--text-secondary)]" }, "mehmet@sirket.com"),
              React.createElement("td", { className: "px-4 py-2.5" }, React.createElement("span", { className: "rounded-full bg-[var(--surface-muted)] px-2 py-0.5 text-xs" }, "Duzenleyici")),
            ),
          ),
        ),
      ),
    ),
  },
  DashboardTemplate: {
    title: "Operasyon Panosu",
    description: "Temel performans metrikleri ve sistem sagligi genel gorunumu.",
    pageWidth: "wide" as const,
    breadcrumbItems: [
      { label: "Ana Sayfa", href: "#" },
      { label: "Pano" },
    ],
    children: React.createElement("div", { className: "flex flex-col gap-4" },
      React.createElement("div", { className: "grid grid-cols-4 gap-3" },
        React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-4" },
          React.createElement("div", { className: "text-xs font-medium uppercase tracking-wider text-[var(--text-secondary)]" }, "Gelir"),
          React.createElement("div", { className: "mt-1 text-2xl font-bold text-[var(--text-primary)]" }, "₺1.24M"),
          React.createElement("div", { className: "mt-1 text-xs text-[var(--status-success))]" }, "\u{2191} %12.3 gecen aya gore"),
        ),
        React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-4" },
          React.createElement("div", { className: "text-xs font-medium uppercase tracking-wider text-[var(--text-secondary)]" }, "Aktif Kullanici"),
          React.createElement("div", { className: "mt-1 text-2xl font-bold text-[var(--text-primary)]" }, "8.432"),
          React.createElement("div", { className: "mt-1 text-xs text-[var(--status-success))]" }, "\u{2191} %5.7 gecen aya gore"),
        ),
        React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-4" },
          React.createElement("div", { className: "text-xs font-medium uppercase tracking-wider text-[var(--text-secondary)]" }, "Calisma Suresi"),
          React.createElement("div", { className: "mt-1 text-2xl font-bold text-[var(--status-success))]" }, "%99.97"),
          React.createElement("div", { className: "mt-1 text-xs text-[var(--text-secondary)]" }, "Son 30 gun"),
        ),
        React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-4" },
          React.createElement("div", { className: "text-xs font-medium uppercase tracking-wider text-[var(--text-secondary)]" }, "Acik Talepler"),
          React.createElement("div", { className: "mt-1 text-2xl font-bold text-[var(--status-warning))]" }, "23"),
          React.createElement("div", { className: "mt-1 text-xs text-[var(--status-error))]" }, "\u{2191} 3 dunden beri"),
        ),
      ),
    ),
  },
  DetailTemplate: {
    title: "Siparis #SIP-2024-1847",
    description: "Siparis detay gorunumu.",
    breadcrumbItems: [
      { label: "Siparisler", href: "#" },
      { label: "#SIP-2024-1847" },
    ],
    children: React.createElement("div", { className: "flex flex-col gap-4" },
      React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-4" },
        React.createElement("div", { className: "flex items-center justify-between mb-3" },
          React.createElement("div", null,
            React.createElement("div", { className: "text-base font-semibold text-[var(--text-primary)]" }, "Acme Teknoloji A.S."),
            React.createElement("div", { className: "text-sm text-[var(--text-secondary)]" }, "Kurumsal Musteri — Istanbul, TR"),
          ),
          React.createElement("span", { className: "rounded-full bg-[color-mix(in_oklab,var(--status-success))_10%,transparent)] px-3 py-1 text-xs font-medium text-[var(--status-success))]" }, "Teslim Edildi"),
        ),
        React.createElement("div", { className: "grid grid-cols-3 gap-4 text-sm" },
          React.createElement("div", null, React.createElement("span", { className: "text-xs text-[var(--text-secondary)]" }, "Siparis Tarihi"), React.createElement("div", { className: "font-medium" }, "2024-03-15")),
          React.createElement("div", null, React.createElement("span", { className: "text-xs text-[var(--text-secondary)]" }, "Toplam Tutar"), React.createElement("div", { className: "font-medium" }, "₺45.200,00")),
          React.createElement("div", null, React.createElement("span", { className: "text-xs text-[var(--text-secondary)]" }, "Odeme"), React.createElement("div", { className: "font-medium" }, "Havale/EFT")),
        ),
      ),
    ),
  },
  SettingsTemplate: {
    title: "Organizasyon Ayarlari",
    description: "Organizasyon tercihleri, guvenlik ve bildirim politikalarini yapilandirin.",
    stickyHeader: true,
    breadcrumbItems: [
      { label: "Yonetim", href: "#" },
      { label: "Ayarlar" },
    ],
    children: React.createElement("div", { className: "flex flex-col gap-4" },
      React.createElement("div", { className: "flex gap-4 border-b border-[var(--border-subtle)] pb-2 text-sm" },
        React.createElement("span", { className: "border-b-2 border-[var(--action-primary))] pb-2 font-medium text-[var(--action-primary))]" }, "Genel"),
        React.createElement("span", { className: "pb-2 text-[var(--text-secondary)] cursor-pointer" }, "Guvenlik"),
        React.createElement("span", { className: "pb-2 text-[var(--text-secondary)] cursor-pointer" }, "Bildirimler"),
      ),
      React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-4" },
        React.createElement("div", { className: "text-sm font-semibold text-[var(--text-primary)] mb-4" }, "Organizasyon Profili"),
        React.createElement("div", { className: "flex flex-col gap-3" },
          React.createElement("div", { className: "flex items-center justify-between" },
            React.createElement("div", null,
              React.createElement("div", { className: "text-sm font-medium" }, "Organizasyon Adi"),
              React.createElement("div", { className: "text-xs text-[var(--text-secondary)]" }, "Acme Teknoloji A.S."),
            ),
            React.createElement("button", { className: "rounded-lg border border-[var(--border-subtle)] px-3 py-1 text-xs" }, "Duzenle"),
          ),
          React.createElement("div", { className: "border-t border-[var(--border-subtle)] pt-3 flex items-center justify-between" },
            React.createElement("div", null,
              React.createElement("div", { className: "text-sm font-medium" }, "Varsayilan Saat Dilimi"),
              React.createElement("div", { className: "text-xs text-[var(--text-secondary)]" }, "Europe/Istanbul (UTC+3)"),
            ),
            React.createElement("button", { className: "rounded-lg border border-[var(--border-subtle)] px-3 py-1 text-xs" }, "Duzenle"),
          ),
        ),
      ),
    ),
  },
  CommandWorkspace: {
    title: "Komut Merkezi",
    description: "Arama, son calismalara gozatin ve birlesik calisma alanindan islemleri yurutun.",
    pageWidth: "wide" as const,
    stickyHeader: true,
    breadcrumbItems: [
      { label: "Calisma Alani", href: "#" },
      { label: "Komutlar" },
    ],
    children: React.createElement("div", { className: "flex flex-col gap-4" },
      React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-3" },
        React.createElement("div", { className: "flex items-center gap-2 rounded-lg bg-[var(--surface-muted)] px-3 py-2" },
          React.createElement("span", { className: "text-[var(--text-secondary)]" }, "\u{1F50D}"),
          React.createElement("span", { className: "text-sm text-[var(--text-secondary)]" }, "Komut, varlik veya islem ara..."),
          React.createElement("span", { className: "ml-auto rounded-xs border border-[var(--border-subtle)] bg-[var(--surface-default))] px-1.5 py-0.5 text-[10px] text-[var(--text-secondary)]" }, "\u{2318}K"),
        ),
      ),
      React.createElement("div", { className: "grid grid-cols-2 gap-4" },
        React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-4" },
          React.createElement("div", { className: "mb-3 text-sm font-semibold text-[var(--text-primary)]" }, "Son Calismalar"),
          React.createElement("div", { className: "flex flex-col gap-2" },
            React.createElement("div", { className: "flex items-center gap-2 rounded-lg bg-[var(--surface-muted)] px-3 py-2 text-xs cursor-pointer" },
              React.createElement("span", { className: "rounded-xs bg-[color-mix(in_oklab,var(--action-primary))_10%,transparent)] px-1.5 py-0.5 text-[10px] font-medium text-[var(--action-primary))]" }, "SIPARIS"),
              React.createElement("span", { className: "font-medium" }, "#SIP-2024-1847"),
              React.createElement("span", { className: "ml-auto text-[var(--text-secondary)]" }, "2 dk once"),
            ),
            React.createElement("div", { className: "flex items-center gap-2 rounded-lg bg-[var(--surface-muted)] px-3 py-2 text-xs cursor-pointer" },
              React.createElement("span", { className: "rounded-xs bg-[color-mix(in_oklab,var(--status-success))_10%,transparent)] px-1.5 py-0.5 text-[10px] font-medium text-[var(--status-success))]" }, "KULLANICI"),
              React.createElement("span", { className: "font-medium" }, "Ayse Demir"),
              React.createElement("span", { className: "ml-auto text-[var(--text-secondary)]" }, "15 dk once"),
            ),
          ),
        ),
        React.createElement("div", { className: "rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-default))] p-4" },
          React.createElement("div", { className: "mb-3 text-sm font-semibold text-[var(--text-primary)]" }, "Hizli Islemler"),
          React.createElement("div", { className: "grid grid-cols-2 gap-2" },
            React.createElement("button", { className: "rounded-lg border border-[var(--border-subtle)] px-3 py-2 text-xs text-left hover:bg-[var(--surface-muted)]" }, "Yeni Rapor"),
            React.createElement("button", { className: "rounded-lg border border-[var(--border-subtle)] px-3 py-2 text-xs text-left hover:bg-[var(--surface-muted)]" }, "Kullanici Ekle"),
            React.createElement("button", { className: "rounded-lg border border-[var(--border-subtle)] px-3 py-2 text-xs text-left hover:bg-[var(--surface-muted)]" }, "Dagitim Yap"),
            React.createElement("button", { className: "rounded-lg border border-[var(--border-subtle)] px-3 py-2 text-xs text-left hover:bg-[var(--surface-muted)]" }, "Veri Aktar"),
          ),
        ),
      ),
    ),
  },
};

