import { getBlock } from '../../blocks/registry';
import type { BlockMeta } from '../../blocks/types';

export interface AddResult {
  success: boolean;
  block: BlockMeta | null;
  message: string;
  files: string[];
}

/**
 * Generate block scaffold code from registry metadata.
 * Returns the code string and list of files that would be created.
 */
export function generateBlockCode(blockId: string): AddResult {
  const block = getBlock(blockId);
  if (!block) {
    return { success: false, block: null, message: `Block "${blockId}" not found in registry.`, files: [] };
  }

  const componentImports = block.components.map(c => c).join(', ');
  const code = [
    `'use client';`,
    ``,
    `import { ${componentImports} } from '@mfe/design-system';`,
    ``,
    `/**`,
    ` * ${block.name} — ${block.description}`,
    ` * Generated by @mfe/ds CLI`,
    ` */`,
    `export function ${block.name}() {`,
    `  return (`,
    `    <div className="flex flex-col gap-4">`,
    ...block.components.map(c => `      <${c} />`),
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `${block.name}.displayName = '${block.name}';`,
  ].join('\n');

  const files = [
    `src/blocks/${block.id}/${block.name}.tsx`,
    `src/blocks/${block.id}/index.ts`,
  ];

  return { success: true, block, message: `Block "${block.name}" ready. Uses: ${componentImports}`, files };
}
